### ISSUE TITLE
Como puedo implementarlo en mi sistema?

### ISSUE THREAD

**Issue by henrypandales** [giansalex/sunat-cdr-status#1]
Atento saludo, quiero implementar este codigo en mi sistema de facturación
http://chamansos.com/ecyberx
Usuario: henry
Clave: henry

Por favor escribeme al whatsapp +57 314 775 4208
que estoy un poco perdido

**Comment by giansalex** [comment]
Hola, actualmente existe otra forma para consultar el status de comprobantes, con la [Consulta integrada de comprobantes](https://orientacion.sunat.gob.pe/images/imagenes/contenido/comprobantes/Manual-de-Consulta-Integrada-de-Comprobante-de-Pago-por-ServicioWEB.pdf)
